import { ArrowLeft, Bold, Code, Eye, Image, Italic, Link as LinkIcon, List, ListOrdered, Quote, Save, Underline } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { categories, savePost, uploadCover } from '../lib/posts'

const blank = { title: '', slug: '', excerpt: '', category: 'Новости', tags: '', cover_url: '', content: '', status: 'draft', featured: false, recommended: false, reading_minutes: 3 }
export default function Editor({ post, onClose }) {
  const [form, setForm] = useState(() => ({ ...blank, ...post, tags: Array.isArray(post?.tags) ? post.tags.join(', ') : post?.tags || '', content: post?.content || localStorage.getItem('thugger_editor_recovery') || '' })), [preview, setPreview] = useState(false), [saving, setSaving] = useState(false), [notice, setNotice] = useState(''); const body = useRef(null)
  const update = (key, value) => setForm((old) => ({ ...old, [key]: value }))
  const command = (name, value = null) => { document.execCommand(name, false, value); body.current?.focus() }
  useEffect(() => { const timer = setTimeout(() => localStorage.setItem('thugger_editor_recovery', form.content || ''), 500); return () => clearTimeout(timer) }, [form.content])
  async function submit(status) { setSaving(true); try { const content = body.current?.innerHTML || form.content; const published_at = status === 'published' ? (form.published_at || new Date().toISOString()) : form.published_at; await savePost({ ...form, content, status, published_at }); localStorage.removeItem('thugger_editor_recovery'); setNotice('Сохранено'); setTimeout(onClose, 500) } catch (e) { setNotice(e.message) } finally { setSaving(false) } }
  async function cover(e) { const file = e.target.files[0]; if (!file) return; update('cover_url', await uploadCover(file)) }
  return <div className="editor"><header><button className="back" onClick={onClose}><ArrowLeft/>К публикациям</button><div><button onClick={() => setPreview(!preview)}><Eye/>Предпросмотр</button><button onClick={() => submit('draft')}><Save/>Черновик</button><button className="primary" disabled={saving} onClick={() => submit('published')}>Опубликовать</button></div></header>{preview ? <article className="article preview"><span className="category">{form.category}</span><h1>{form.title || 'Заголовок публикации'}</h1><p>{form.excerpt}</p>{form.cover_url && <img className="article-cover" src={form.cover_url}/>}<div className="prose" dangerouslySetInnerHTML={{ __html: body.current?.innerHTML || form.content }}/></article> : <div className="editor-grid"><section><label>Заголовок<input value={form.title} onChange={(e) => { update('title', e.target.value); if (!post) update('slug', e.target.value.toLowerCase().replace(/[^a-zа-яё0-9]+/gi, '-').replace(/^-|-$/g, '')) }}/></label><label>Краткое описание<textarea value={form.excerpt} onChange={(e) => update('excerpt', e.target.value)}/></label><div className="toolbar"><button onClick={() => command('bold')} title="Жирный"><Bold/></button><button onClick={() => command('italic')}><Italic/></button><button onClick={() => command('underline')}><Underline/></button><button onClick={() => command('formatBlock', 'blockquote')}><Quote/></button><button onClick={() => command('insertUnorderedList')}><List/></button><button onClick={() => command('insertOrderedList')}><ListOrdered/></button><button onClick={() => command('formatBlock', 'pre')}><Code/></button><button onClick={() => command('createLink', prompt('Введите ссылку'))}><LinkIcon/></button></div><div ref={body} className="rich" contentEditable suppressContentEditableWarning onInput={(e) => update('content', e.currentTarget.innerHTML)} dangerouslySetInnerHTML={{ __html: form.content }}/></section><aside><label>Обложка<div className="upload">{form.cover_url ? <img src={form.cover_url}/> : <><Image/><span>Выбрать изображение</span></>}<input type="file" accept="image/*" onChange={cover}/></div></label><label>Адрес статьи<input value={form.slug} onChange={(e) => update('slug', e.target.value)}/></label><label>Категория<select value={form.category} onChange={(e) => update('category', e.target.value)}>{categories.slice(1).map((c) => <option key={c}>{c}</option>)}</select></label><label>Теги<input value={form.tags} onChange={(e) => update('tags', e.target.value)} placeholder="боты, релиз"/></label><label><input type="checkbox" checked={form.featured} onChange={(e) => update('featured', e.target.checked)}/> Закрепить публикацию</label><label><input type="checkbox" checked={form.recommended} onChange={(e) => update('recommended', e.target.checked)}/> Добавить в рекомендации</label>{notice && <p className="notice">{notice}</p>}</aside></div>}</div>
}
